### ISSUE TITLE
Unsure about expected behavior of area randomization 

### ISSUE THREAD

**Issue by ChristoWolf** [ChaoticBrave/VagrantStoryRandomizer#2]
Hi @ChaoticBrave!

I have started 2 seeds, but I don't remember the exact settings that I used.
For the first I explicitly **enabled** area randomization, for the second I left it **disabled**.
Both led to the same behavior though: Leaving the wine cellar after Durandal gave the Keep as the new area.
Going back did not bring me back to the wine cellar, but to somewhere entirely different.

Not sure about the intended behavior, but I have the following questions for now:
- Areas should of course be as in the vanilla game when area randomization is disabled, right?
- Area connections should be consistent, right? I.e. when i came from area X, going back through the same door should bring me back there and not to some entirely different area, right?
- Area randomization should depend on the seed. For 2 different seeds I got the exact same room orders. I know that that's a statistical possibility, but quite unlikely.

If you need to know the exact settings and seeds, please let me know.

Version: 0.8.8.0
Observed with PCSX ReARMed.

**Comment by ChaoticBrave** [comment]
Hello @ChristoWolf,

Thanks for your feedback. Anything goes a long way to helping my project be the best it can be. With the second seed you made where you deselected the area randomisation, did you use the Revert to Vanilla option at all? If you didn't, then an already randomised game will not change back. Though I could look into making things different there.

Rather guiltily, I never thought to make backwards area travel consistent. I should really have done that from the beginning. Perhaps I was so desperate to get area randomisation working at all that it never crossed my mind. I will implement this when I next work on the randomizer.   

Sorry for any inconveniences which this may have caused.

**Comment by ChristoWolf** [comment]
Hey @ChaoticBrave, thanks for the quick response!

Hmm, I keep my original and randomized ISOs all in separate places, but this might actually be the cause, thanks for the hint!

No worries, good to know that this is currently expected behavior.

I will try it more, as it is a lot of fun, and will report anything that I find.

**Comment by ChaoticBrave** [comment]
Hey @ChristoWolf 

Sorry I couldn't respond any sooner with my first message; Christmas Eve and Christmas Day were busier than I expected. 

Thanks for your kind words about the randomizer. While the behaviour is expected with area randomisation, I'd hesitate to say if it's ideal if you had questions about it. Perhaps I could be using my tool tips more efficiently there.

**Comment by ChristoWolf** [comment]
Hey no worries, hope you are having great holidays!

I now tried again with a completely fresh, untouched ISO and with area randomization disabled, but I experienced the exact same issue unfortunately.

**Comment by ChaoticBrave** [comment]
Thank you, I hope you're enjoying your holidays as well.

As for your issue, that can be explained by the MAP folder still using the contents of your first randomisation. The Revert to Vanilla button should remedy this.

I should definitely make this less obtuse.

**Comment by ChristoWolf** [comment]
That was exactly the issue, thanks for the help!
I really wouldn't have expected the tool to store state of unrelated binaries.

**Comment by ChaoticBrave** [comment]
I'm really not that clever to pull such a thing off! Perhaps it's better that way.

**Comment by ChaoticBrave** [comment]
You can now return to the previous area from the randomized one in v0.8.82.0.

**Comment by ChristoWolf** [comment]
Awesome, thanks!
