### ISSUE TITLE
Randomized weapons might have incompatible grips

### ISSUE THREAD

**Issue by ChristoWolf** [ChaoticBrave/VagrantStoryRandomizer#4]
**TODO**

**Comment by ChaoticBrave** [comment]
Is the TODO for me or for you?

**Comment by ChristoWolf** [comment]
For me, just didn't have time yet to write up some details.
Not sure if that's really needed here though, as it's something that happens very commonly.

**Comment by ChaoticBrave** [comment]
Do you have an example of this sort of thing? Just to give me something to work with when fixing this.

**Comment by ChaoticBrave** [comment]
The issue has been discovered and fixed in v0.8.82.0.

**Comment by ChristoWolf** [comment]
Awesome, thanks!
