### ISSUE TITLE
Randomized blades might be made of non-weapon materials 

### ISSUE THREAD

**Issue by ChristoWolf** [ChaoticBrave/VagrantStoryRandomizer#5]
Accordingly, affected blades are rendered without textures, because there are no matching ones for the material. 

E.g.:

![Img_2024_01_02_20_56_23](https://github.com/ChaoticBrave/VagrantStoryRandomizer/assets/52244643/7266b3df-0b34-4552-a80a-113aff5f08d9)

As you can see in the screenshot, armor pieces might also be made of unsupported materials (here: wooden gloves).
Do you want me to document this in a separate, dedicated issue? 

Version: 0.8.8.0

**Comment by ChaoticBrave** [comment]
The issue has been discovered and fixed in v0.8.82.0.

**Comment by ChristoWolf** [comment]
Awesome, thanks!
